### PR TITLE
limit test/clean execution to 10s

### PR DESCRIPTION
**Pull request by makk94**
re: https://github.com/preludeorg/libraries/issues/261

### CODE REVIEW

**Review by privateducky — COMMENTED** [review]
this is great; let me know when it works!

**Comment by makk94** [comment]
Works for me!
Tested by adding time.Sleep() statements in test() and clean() functions of 021a1dbf-e080-495c-937e-7fa79d39bf30 and getting 102s and exiting
```
mahinakaholokula@Mahinas-MacBook-Pro 021a1dbf-e080-495c-937e-7fa79d39bf30 % go run 021a1dbf-e080-495c-937e-7fa79d39bf30.go
[+] Starting test
exit status 102
mahinakaholokula@Mahinas-MacBook-Pro 021a1dbf-e080-495c-937e-7fa79d39bf30 % 
```

**Review by mireaulf — APPROVED** [review]

**Comment by bfuzzy1** [comment]
The team and I will need to test across all VSTs before this is merged. Great PR though thank you!

**Review by privateducky — APPROVED** [review]

**Comment by bfuzzy1** [comment]
Plan is to test this one out tomorrow!

**Review by privateducky — APPROVED** [review]
great work. exactly what I'd have done.

**Pull request merged**
