### PR TITLE
rule: block network req from spec countries

### PR DESCRIPTION
**Pull request by privateducky**
Rule: Block outbound network requests to specific countries

### CODE REVIEW

**Comment by bfuzzy1** [comment]
Just hangs when executed on most systems thus far. Looking into as to why that is happening now.

**Comment by privateducky** [comment]
> Just hangs when executed on most systems thus far. Looking into as to why that is happening now even with internet disabled.

Can you redownload the Endpoint module and try again?
```
go get -u github.com/preludeorg/test/endpoint
```

**Comment by bfuzzy1** [comment]
> > Just hangs when executed on most systems thus far. Looking into as to why that is happening now even with internet disabled.
> 
> Can you redownload the Endpoint module and try again?
> 
> ```
> go get -u github.com/preludeorg/test/endpoint
> ```

Same. 

@VVX7 was thinking it might be caused by blocking read as a test I added a 20 second deadline to read reply and it hits the timeout.

Screenshot 2023-01-13 at 3 32 58 PM

**Comment by VVX7** [comment]
modified `DialTCP` to use bufio reader

**Comment by bfuzzy1** [comment]
> modified `DialTCP` to use bufio reader

All tests are passing with this new change.

Tested:

```
Darwin arm64 test passed
Windows 11 arm64 test passed
Fedora 36 arm64 test passed
Debian 11.3 arm64 test passed
Ubuntu 22.04 ARM64 test passed
Windows 11 x64 test passed
Windows 10 x64 test passed
Windows Server 2016 test passed
Windows Server 2019 test passed
Ubuntu 22.04 amd64 test passed
Ubuntu 22.10 amd64 test passed
```

**Comment by privateducky** [comment]
merge conflicts

**Comment by privateducky** [comment]
> merge conflicts

@bfuzzy1 bump

**Pull request closed without merging**
